Реализация основной части ТЗ дипломного проекта
Alekseev-s1/java-explore-with-me pull request #1
Opened 2022-10-29 18:42 UTC by Alekseev-s1

2022-10-31 16:02 UTC, sergeymamonov requested changes

2022-10-31 16:02 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explore/exception/ErrorHandler.java
> +    public ResponseEntity<ApiError> handleInitiatorIsOwner(InitiatorIsOwnerException e) {
Методы отличаются только принимаемой ошибкой. Воспользуйтесь наследованием, чтобы метод принимал родительский класс. И тогда не нужно будет делать столько одинаковых методов.

2022-10-31 16:02 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explore/exception/ErrorHandler.java
> +    }
Лучше еще обработать рантайм ошибки.

2022-10-31 16:02 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explore/exception/UnitNotFoundException.java
> +    public static Supplier<UnitNotFoundException> unitNotFoundException(String message, Object... args) {
Зачем нужно делать такой метод? Почему нельзя сделать строку в вызывающем коде и передавать только строку? Тогда одного конструктора, который на строках 6-9 будет достаточно.

2022-10-31 16:02 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explore/mapper/mapstruct/CompilationMapper.java
> +import org.mapstruct.Mapper;
Не очень понимаю, зачем конвертеры сделаны самостоятельно и с помощью Mapstruct? Какими конвертерами планируется пользоваться?

2022-11-01 18:58 UTC, Alekseev-s1 commented on main-service/src/main/java/ru/practicum/explore/exception/UnitNotFoundException.java
> +    public static Supplier<UnitNotFoundException> unitNotFoundException(String message, Object... args) {
Подобный подход обнаружил в статье одного из наставников, решил использовать в этом проекте.

https://struchkov.dev/blog/optional-in-java/#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-orelsethrowsupplier-s

2022-11-01 18:58 UTC, Alekseev-s1 commented on main-service/src/main/java/ru/practicum/explore/mapper/mapstruct/CompilationMapper.java
> +import org.mapstruct.Mapper;
Mapstruct был добавлен изначально в экспериментальных целях, забыл удалить перед проверкой. Использоваться будет конвертер, сделанный самостоятельно.

2022-11-02 13:17 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explore/mapper/mapstruct/CompilationMapper.java
> +import org.mapstruct.Mapper;
Если вы уже знаете, что есть Mapstruct и даже начали им пользоваться, зачем же откатываться к самостоятельному написанию конвертеров?)

2022-11-02 13:20 UTC, sergeymamonov approved these changes

2022-11-04 08:55 UTC, Alekseev-s1 commented on main-service/src/main/java/ru/practicum/explore/mapper/mapstruct/CompilationMapper.java
> +import org.mapstruct.Mapper;
Я пока что знаком с Mapstruct на уровне осведомленности о его существовании. Есть пара методов конвертации, например, `toEvent(NewEventDto newEventDto, Category category)`, которые мне на данный момент удобнее сделать с помощью самостоятельного конвертера.
В ближайшем будущем планирую ближе познакомиться с Mapstruct и полностью перейти на него.

2022-11-04 09:01 UTC, merged